### ISSUE TITLE
Implement the Communicator for Web

### ISSUE THREAD

**Issue by raksanyi** [Isabelle2048/CorEstafette#7]
1. Needs to be able to connect to the service via wss
2. After successful connection, the communicator has to send their client name to the service, so the service knows which connection belongs to which client name
3. When the client wants to subscribe to a topic with a callback, the communicator has to cache topic-callback pairs, so when a publish comes to that topic, it would know which callback to invoke
4. When subscribing or unsubscribing, the communicator has to wait for an answer from the service
5. Publish should be fire&forget, so no waiting for response is needed

**Comment by Isabelle2048** [comment]
Publish method implemented in communicator under webCommunicator branch. Web client can now publish a message and be heard by other clients connected to the same hub.

**Comment by Isabelle2048** [comment]
Hi Robert I wonder if you could please help me with these:
1. Could you review the new commits in convertToTs branch? specifically, I am not sure about whether I am doing the right thing with getting the response in subscribeAsync() in communicator.ts.
2. Can a message have multiple topics? (In this case, we need to add logics in hub, in order to avoid duplicated send)
3. If a client has registered a callback with a topic, can it change the callback to the same topic later?
Thank you!

**Comment by raksanyi** [comment]
Hi,
I'll review the commits. For 2., this will come with the pattern-based subscriptions (e.g. topicA/topicB/*), so likely the hub subscription logic will have to be changed later. For 3., "changing" the callback will require the client to unsubscribe first, and then resubscribe with a different callback.
